version: 2.1
jobs:
 week9-taskOne:
    docker:
      - image: circleci/node:12

    steps:
      - checkout
      - run: npm install
      - run: npx tsc
      - run: npm test
workflows:
    build_test:
        jobs:
            - week9-taskOne